### ISSUE TITLE
Got an error when command line completion is configured

### ISSUE THREAD

**Issue by glassesneo** [Shougo/pum.vim#64]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
I got an error when setting the config for the command line completion via pum.vim and ddc-ui-pum **whereas its completion still works.**

## Environment Information (Required!)

- pum.vim version(SHA1):
fd14ce2c1d4a378d50b6532bb05e7ad7935930c1

- OS:
MacOS Sonoma 14.6.1

- neovim/Vim `:version` output:
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dpp/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dpp/repos/github.com/Shougo/ddc.vim
set rtp+=~/.cache/dpp/repos/github.com/Shougo/pum.vim
set rtp+=~/.cache/dpp/repos/github.com/Shougo/ddc-ui-pum
set rtp+=~/.cache/dpp/repos/github.com/Shougo/ddc-source-cmdline
set rtp+=~/.cache/dpp/repos/github.com/Shougo/ddc-filter-matcher_head
set rtp+=~/.cache/dpp/repos/github.com/Shougo/ddc-filter-sorter_rank

lua <<EOF
local function map(mode, lhs, rhs, opts)
  vim.keymap.set(mode, lhs, rhs, opts or {})
end

local function unmap(mode, lhs, opts)
  vim.keymap.del(mode, lhs, opts or {})
end

vim.fn["ddc#custom#patch_global"]({
  ui = "pum",
  autoCompleteEvents = {
    "CmdlineEnter",
    "CmdlineChanged",
  },
  cmdlineSources = {
    [":"] = {"cmdline"},
  },
  sourceOptions = {
    cmdline = {
      mark = "[>_]",
      matchers = {"matcher_head"},
      sorters = {"sorter_rank"},
      converters = {},
      forceCompletionPattern = [[\S/\S*|\.\w*]],
    },
  },
})
vim.fn["ddc#enable"]()

local pum_forward = function()
  vim.fn["pum#map#insert_relative"](1, "loop")
end
local pum_backward = function()
  vim.fn["pum#map#insert_relative"](-1, "loop")
end
local pum_confirm = function()
  vim.fn["pum#map#confirm"]()
end

map("n", ":", "<Cmd>CommandlinePre<CR>:")

vim.api.nvim_create_user_command("CommandlinePre", function()
  map("c", "<C-n>", pum_forward)
  map("c", "<C-p>", pum_backward)
  map("c", "<C-y>", pum_confirm)

  vim.api.nvim_create_autocmd({ "User" }, {
    pattern = "DDCCmdlineLeave",
    once = true,
    callback = function()
      unmap("c", "<C-n>", { silent = true })
      unmap("c", "<C-p>", { silent = true })
      unmap("c", "<C-y>", { silent = true })
    end,
  })
  vim.fn["ddc#enable_cmdline_completion"]()
end, {})
EOF
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start Neovim with the config above
2. See the error using `:messages`

## Screen shot (if possible)
![スクリーンショット 2024-09-30 13 11 20](https://github.com/user-attachments/assets/e80374ce-3186-4af7-90d1-d3e470dd12e8)

## Upload the log messages by `:redir` and `:message` (if errored)
```
[denops] Failed to handle message 2,invoke,dispatch,ddc,onEvent,CmdlineChanged Error: Failed to call 'onEvent' API in 'ddc': Failed to call 'pum#open' in N
eovim: function pum#open[13]..pum#popup#_open, line 400: Vim(autocmd):E216: そのようなイベントはありません: CursorMovedC * ++once ++nested call pum#close()
 (code: 0)
[denops]     at Plugin.call (file:///Users/neo/.cache/dpp/repos/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:279:13)
[denops]     at eventLoopTick (ext:core/01_core.js:168:7)
[denops]     at async Service.#dispatch (file:///Users/neo/.cache/dpp/repos/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:117:12)
[denops]     at async Service.dispatch (file:///Users/neo/.cache/dpp/repos/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:123:14)
[denops]     at async dispatch (https://jsr.io/@lambdalisue/messagepack-rpc/2.4.0/dispatcher.ts:36:12)
[denops]     at async Session.#dispatch (https://jsr.io/@lambdalisue/messagepack-rpc/2.4.0/session.ts:255:22)
[denops]     at async Session.#handleNotificationMessage (https://jsr.io/@lambdalisue/messagepack-rpc/2.4.0/session.ts:310:25)
[denops] Failed to handle message 2,invoke,dispatch,ddc,onEvent,CmdlineChanged Error: Failed to call 'onEvent' API in 'ddc': Failed to call 'pum#open' in N
eovim: function pum#open[13]..pum#popup#_open, line 400: Vim(autocmd):E216: そのようなイベントはありません: CursorMovedC * ++once ++nested call pum#close()
 (code: 0)
[denops]     at Plugin.call (file:///Users/neo/.cache/dpp/repos/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:279:13)
[denops]     at eventLoopTick (ext:core/01_core.js:168:7)
[denops]     at async Service.#dispatch (file:///Users/neo/.cache/dpp/repos/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:117:12)
[denops]     at async Service.dispatch (file:///Users/neo/.cache/dpp/repos/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:123:14)
[denops]     at async dispatch (https://jsr.io/@lambdalisue/messagepack-rpc/2.4.0/dispatcher.ts:36:12)
[denops]     at async Session.#dispatch (https://jsr.io/@lambdalisue/messagepack-rpc/2.4.0/session.ts:255:22)
[denops]     at async Session.#handleNotificationMessage (https://jsr.io/@lambdalisue/messagepack-rpc/2.4.0/session.ts:310:25)
```

**Comment by 4513ECHO** [comment]
Your neovim is old (CursorMovedC autocmd is implemented nightly), but as long as pum.vim declares support for neovim 0.8.0 or later, pum.vim should check the version.

**Comment by Shougo** [comment]
Fixed.
